### ISSUE TITLE
L1 - TvSettings - VTS Test case bugs - Tag 1.3.0

### ISSUE THREAD

**Issue by Anbukannadhasan** [rdkcentral/rdkv-halif-test-tvsettings#24]
Bank 6:
- The color temperature RGB gain test cases range is from 0 to 2047. VTS handles only values from 1 to 2047. Correction is required.
- In the test_l1_tvSettings_positive_GetColorTemp_Ggain_onSource test case, the variable is incorrectly compared.

Bank 7:

- For all component color test cases, tvDataColor_NONE is not a valid parameter. Correction is required in the YAML file.
- The size of the Gamma Table is incorrectly specified. Correction is required.
- In SaveGammaTable, for the positive test case, the error code is wrongly compared with "Invalid param."
- In test_l1_tvSettings_negative_GetDefaultGammaTable, the color temperature index value is incorrectly assigned and parsed.

Test suite name correction required for test_l1_tvSettings_positive_GetPQParams

**Comment by srinivasgtl** [comment]
This issue is now considered as part of #31
