### ISSUE TITLE
TvSettings:  L1 Issues found 1.3.0

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdkv-halif-test-tvsettings#31]
Fixing issues found during 1.3.0 test 
(addressing Issue #24 as well in this ticket.)
Bank 6:
- Issue in L1  reading color temperature data from profile
- The color temperature RGB gain test cases range is from 0 to 2047. VTS handles only values from 1 to 2047. Correction is required.

Bank 7:
- In the test_l1_tvSettings_positive_GetColorTemp_Ggain_onSource test case, the variable is incorrectly compared.
- For all component color test cases, tvDataColor_NONE is not a valid parameter. Correction is required in the YAML file.
- The size of the Gamma Table is incorrectly specified. Correction is required.
- In SaveGammaTable, for the positive test case, the error code is wrongly compared with "Invalid param."
- In test_l1_tvSettings_negative_GetDefaultGammaTable, the color temperature index value is incorrectly assigned and parsed.

Test suite name correction required for test_l1_tvSettings_positive_GetPQParams

**Comment by hari22yuva** [comment]
merged and tag 1.3.1
