### ISSUE TITLE
Adding new config index and handle issues

### ISSUE THREAD

**Issue by ranjithkumarkp** [rdkcentral/rdkv-halif-test-tvsettings#6]
1. Issue in tvDataComponentColor_t set (Hue_Luma_Saturation )
2. SetAspectRatio  ORed input parameter issue
3. Index token included in config file (DimmingMode, BacklightControl, DolbyVisionMode and aspect ratio)
4.  videosource is "composite" added additional check
5. tvComponentType_t add in config file 
6. EnableDynamicContrast api change

**Comment by hari22yuva** [comment]
merged to develop
