### ISSUE TITLE
The test case L2 GetTVGammaTarget fails due to the loop iterating over all possible enum values instead of the supported color temperature values.

### ISSUE THREAD

**Issue by Anbukannadhasan** [rdkcentral/rdkv-halif-test-tvsettings#61]
### Problem/Opportunity

The test case is failing because the loop in the GetTVGammaTarget function tests all possible enum values, while only four specific color temperature values (STANDARD, WARM, COLD, USER) are supported.

### Steps to reproduce

1. Run the test case test_l2_tvSettings_GetTVGammaTarget.
2. Observe the test output where the loop iterates through all possible enum values for color temperature.
3. The test will fail as the VTS expects only the valid color temperature values.

### Expected Behavior

The loop should only iterate over the four supported color temperature values to ensure compatibility with the VTS, and the test

### Actual Behavior

The test fails because the loop is iterating over all enum values, which includes invalid color temperature values, causing mismatched expectations in the VTS.

**Comment by srinivasgtl** [comment]
Fix available in tag 2.1.3
