### ISSUE TITLE
Correction with saveOnly Parameter Handling in SetColorTemp_RGB gain_onSource and RGB post offset APIs

### ISSUE THREAD

**Issue by Anbukannadhasan** [rdkcentral/rdkv-halif-test-tvsettings#65]
### Problem/Opportunity

he saveOnly parameter is not functioning as expected in the SetColorTemp_RGB gain_onSource and set RGB post off API. When saveOnly = 1, VTS is incorrectly attempting to match the Rgain value via the GetColorTemp_Rgain_onSource API, even though the value is only supposed to be saved in the database and not applied to the hardware. This causes the Get API to fail, as the value saved with saveOnly = 1 should not be expected to immediately match with the current hardware state.

### Expected Behavior

When saveOnly = 1, the Rgain value should be saved into the database but not applied to the hardware immediately.
The GetColorTemp_Rgain_onSource API should not try to match the Rgain value immediately after saveOnly = 1. The saved value should only be retrieved when the corresponding color temperature and source are selected, and it should not fail due to mismatched hardware values.

### Actual Behavior

When saveOnly = 1, the VTS is incorrectly trying to match the Rgain value during a Get operation, causing failures because the saved value in the database is not yet applied to the hardware.

**Comment by srinivasgtl** [comment]
available in tag 2.1.3
